/*
###############################################################
#  Generated by:      Cadence Encounter 11.10-p003_1
#  OS:                Linux x86_64(Host ID flip1.engr.oregonstate.edu)
#  Generated on:      Sun Jun  9 22:29:25 2013
#  Design:            sensor
#  Command:           saveNetlist ../vlogout/final.v -excludeLeafCell -exclu...
###############################################################
*/
module Spare_1 ();

   INVX4 spr_gate4 (.IN(1'b1));
   FADDX1 spr_gate3 (.CI(1'b1), 
	.B(1'b1), 
	.A(1'b1));
   DFFARX1 spr_gate2 (.RSTB(1'b1), 
	.D(1'b1), 
	.CLK(1'b1));
endmodule

module sensor (
	clk, 
	reset_n, 
	sensor, 
	ROM_data, 
	clk_mem, 
	ROM_addr, 
	ROM_re, 
	ROM_ce, 
	LED);
   input clk;
   input reset_n;
   input sensor;
   input [7:0] ROM_data;
   input clk_mem;
   output [3:0] ROM_addr;
   output ROM_re;
   output ROM_ce;
   output LED;

   // Internal wires
   wire restart;
   wire shift_sr;
   wire load_sr;
   wire \counter_sm0/n33 ;
   wire \counter_sm0/n32 ;
   wire \counter_sm0/n31 ;
   wire \counter_sm0/n30 ;
   wire \counter_sm0/n29 ;
   wire \counter_sm0/n28 ;
   wire \counter_sm0/n27 ;
   wire \counter_sm0/n26 ;
   wire \counter_sm0/n25 ;
   wire \counter_sm0/n24 ;
   wire \counter_sm0/n23 ;
   wire \counter_sm0/n22 ;
   wire \counter_sm0/n21 ;
   wire \counter_sm0/n20 ;
   wire \counter_sm0/n19 ;
   wire \counter_sm0/n18 ;
   wire \counter_sm0/n17 ;
   wire \counter_sm0/n16 ;
   wire \counter_sm0/n15 ;
   wire \counter_sm0/n14 ;
   wire \counter_sm0/n13 ;
   wire \counter_sm0/n12 ;
   wire \counter_sm0/n11 ;
   wire \counter_sm0/n8 ;
   wire \counter_sm0/n7 ;
   wire \counter_sm0/n5 ;
   wire \counter_sm0/state[0] ;
   wire \counter_sm0/state[1] ;
   wire \counter_sm0/state[2] ;
   wire \divider_even0/N4 ;
   wire \divider_even0/rout ;
   wire \mem_to_fifo_sm0/n33 ;
   wire \mem_to_fifo_sm0/n32 ;
   wire \mem_to_fifo_sm0/n31 ;
   wire \mem_to_fifo_sm0/n30 ;
   wire \mem_to_fifo_sm0/n29 ;
   wire \mem_to_fifo_sm0/n28 ;
   wire \mem_to_fifo_sm0/n26 ;
   wire \mem_to_fifo_sm0/n25 ;
   wire \mem_to_fifo_sm0/n24 ;
   wire \mem_to_fifo_sm0/n23 ;
   wire \mem_to_fifo_sm0/n22 ;
   wire \mem_to_fifo_sm0/n21 ;
   wire \mem_to_fifo_sm0/n20 ;
   wire \mem_to_fifo_sm0/n19 ;
   wire \mem_to_fifo_sm0/n18 ;
   wire \mem_to_fifo_sm0/n17 ;
   wire \mem_to_fifo_sm0/n16 ;
   wire \mem_to_fifo_sm0/n15 ;
   wire \mem_to_fifo_sm0/n14 ;
   wire \mem_to_fifo_sm0/n12 ;
   wire \mem_to_fifo_sm0/n11 ;
   wire \mem_to_fifo_sm0/n10 ;
   wire \mem_to_fifo_sm0/n9 ;
   wire \mem_to_fifo_sm0/n8 ;
   wire \mem_to_fifo_sm0/n7 ;
   wire \mem_to_fifo_sm0/n6 ;
   wire \mem_to_fifo_sm0/n5 ;
   wire \mem_to_fifo_sm0/N43 ;
   wire \mem_to_fifo_sm0/state[0] ;
   wire \mem_to_fifo_sm0/state[1] ;
   wire \mem_to_fifo_sm0/state[2] ;
   wire \shift_register_sm0/n146 ;
   wire \shift_register_sm0/n145 ;
   wire \shift_register_sm0/n144 ;
   wire \shift_register_sm0/n143 ;
   wire \shift_register_sm0/n142 ;
   wire \shift_register_sm0/n141 ;
   wire \shift_register_sm0/n140 ;
   wire \shift_register_sm0/n139 ;
   wire \shift_register_sm0/n138 ;
   wire \shift_register_sm0/n137 ;
   wire \shift_register_sm0/n136 ;
   wire \shift_register_sm0/n135 ;
   wire \shift_register_sm0/n134 ;
   wire \shift_register_sm0/n133 ;
   wire \shift_register_sm0/n132 ;
   wire \shift_register_sm0/n131 ;
   wire \shift_register_sm0/n130 ;
   wire \shift_register_sm0/n129 ;
   wire \shift_register_sm0/n128 ;
   wire \shift_register_sm0/n127 ;
   wire \shift_register_sm0/n126 ;
   wire \shift_register_sm0/n125 ;
   wire \shift_register_sm0/n124 ;
   wire \shift_register_sm0/n123 ;
   wire \shift_register_sm0/n122 ;
   wire \shift_register_sm0/n121 ;
   wire \shift_register_sm0/n120 ;
   wire \shift_register_sm0/n119 ;
   wire \shift_register_sm0/n118 ;
   wire \shift_register_sm0/n117 ;
   wire \shift_register_sm0/n116 ;
   wire \shift_register_sm0/n115 ;
   wire \shift_register_sm0/n114 ;
   wire \shift_register_sm0/n113 ;
   wire \shift_register_sm0/n112 ;
   wire \shift_register_sm0/n111 ;
   wire \shift_register_sm0/n110 ;
   wire \shift_register_sm0/n109 ;
   wire \shift_register_sm0/n108 ;
   wire \shift_register_sm0/n107 ;
   wire \shift_register_sm0/n106 ;
   wire \shift_register_sm0/n105 ;
   wire \shift_register_sm0/n104 ;
   wire \shift_register_sm0/n103 ;
   wire \shift_register_sm0/n102 ;
   wire \shift_register_sm0/n101 ;
   wire \shift_register_sm0/n100 ;
   wire \shift_register_sm0/n99 ;
   wire \shift_register_sm0/n98 ;
   wire \shift_register_sm0/n97 ;
   wire \shift_register_sm0/n96 ;
   wire \shift_register_sm0/n95 ;
   wire \shift_register_sm0/n94 ;
   wire \shift_register_sm0/n93 ;
   wire \shift_register_sm0/n92 ;
   wire \shift_register_sm0/n91 ;
   wire \shift_register_sm0/n90 ;
   wire \shift_register_sm0/n89 ;
   wire \shift_register_sm0/n88 ;
   wire \shift_register_sm0/n87 ;
   wire \shift_register_sm0/n86 ;
   wire \shift_register_sm0/n85 ;
   wire \shift_register_sm0/n84 ;
   wire \shift_register_sm0/n83 ;
   wire \shift_register_sm0/n82 ;
   wire \shift_register_sm0/n81 ;
   wire \shift_register_sm0/n80 ;
   wire \shift_register_sm0/n79 ;
   wire \shift_register_sm0/n78 ;
   wire \shift_register_sm0/n77 ;
   wire \shift_register_sm0/n76 ;
   wire \shift_register_sm0/n75 ;
   wire \shift_register_sm0/n74 ;
   wire \shift_register_sm0/n73 ;
   wire \shift_register_sm0/n72 ;
   wire \shift_register_sm0/n71 ;
   wire \shift_register_sm0/n70 ;
   wire \shift_register_sm0/n69 ;
   wire \shift_register_sm0/n68 ;
   wire \shift_register_sm0/n67 ;
   wire \shift_register_sm0/n66 ;
   wire \shift_register_sm0/n65 ;
   wire \shift_register_sm0/n64 ;
   wire \shift_register_sm0/n63 ;
   wire \shift_register_sm0/n62 ;
   wire \shift_register_sm0/n61 ;
   wire \shift_register_sm0/n60 ;
   wire \shift_register_sm0/n59 ;
   wire \shift_register_sm0/n58 ;
   wire \shift_register_sm0/n57 ;
   wire \shift_register_sm0/n56 ;
   wire \shift_register_sm0/n55 ;
   wire \shift_register_sm0/n54 ;
   wire \shift_register_sm0/n53 ;
   wire \shift_register_sm0/n52 ;
   wire \shift_register_sm0/n51 ;
   wire \shift_register_sm0/n50 ;
   wire \shift_register_sm0/n49 ;
   wire \shift_register_sm0/n48 ;
   wire \shift_register_sm0/n47 ;
   wire \shift_register_sm0/n46 ;
   wire \shift_register_sm0/n45 ;
   wire \shift_register_sm0/n44 ;
   wire \shift_register_sm0/n43 ;
   wire \shift_register_sm0/n42 ;
   wire \shift_register_sm0/n41 ;
   wire \shift_register_sm0/n40 ;
   wire \shift_register_sm0/n38 ;
   wire \shift_register_sm0/n37 ;
   wire \shift_register_sm0/n36 ;
   wire \shift_register_sm0/n35 ;
   wire \shift_register_sm0/n34 ;
   wire \shift_register_sm0/n33 ;
   wire \shift_register_sm0/n32 ;
   wire \shift_register_sm0/n31 ;
   wire \shift_register_sm0/n30 ;
   wire \shift_register_sm0/n29 ;
   wire \shift_register_sm0/n28 ;
   wire \shift_register_sm0/n27 ;
   wire \shift_register_sm0/n26 ;
   wire \shift_register_sm0/n25 ;
   wire \shift_register_sm0/n24 ;
   wire \shift_register_sm0/n23 ;
   wire \shift_register_sm0/n20 ;
   wire \shift_register_sm0/n19 ;
   wire \shift_register_sm0/n15 ;
   wire \shift_register_sm0/N89 ;
   wire \shift_register_sm0/out[0] ;
   wire \shift_register_sm0/out[1] ;
   wire \shift_register_sm0/out[2] ;
   wire \shift_register_sm0/out[3] ;
   wire \shift_register_sm0/out[4] ;
   wire \shift_register_sm0/out[5] ;
   wire \shift_register_sm0/out[6] ;
   wire \shift_register_sm0/out[7] ;
   wire \shift_register_sm0/out[8] ;
   wire \shift_register_sm0/out[9] ;
   wire \shift_register_sm0/out[10] ;
   wire \shift_register_sm0/out[11] ;
   wire \shift_register_sm0/out[12] ;
   wire \shift_register_sm0/out[13] ;
   wire \shift_register_sm0/out[14] ;
   wire \shift_register_sm0/out[15] ;
   wire \shift_register_sm0/out[16] ;
   wire \shift_register_sm0/out[17] ;
   wire \shift_register_sm0/out[18] ;
   wire \shift_register_sm0/out[19] ;
   wire \shift_register_sm0/out[20] ;
   wire \shift_register_sm0/out[21] ;
   wire \shift_register_sm0/out[22] ;
   wire \shift_register_sm0/out[23] ;
   wire \shift_register_sm0/out[24] ;
   wire \shift_register_sm0/out[25] ;
   wire \shift_register_sm0/out[26] ;
   wire \shift_register_sm0/out[27] ;
   wire \shift_register_sm0/out[28] ;
   wire \shift_register_sm0/out[29] ;
   wire \shift_register_sm0/out[30] ;
   wire \shift_register_sm0/out[31] ;
   wire \shift_register_sm0/state[0] ;
   wire \shift_register_sm0/state[1] ;
   wire \shift_register_sm0/state[2] ;
   wire \shift_register_sm0/state[3] ;
   wire \shift_register0/n41 ;
   wire \shift_register0/n40 ;
   wire \shift_register0/n39 ;
   wire \shift_register0/n38 ;
   wire \shift_register0/n37 ;
   wire \shift_register0/n36 ;
   wire \shift_register0/n35 ;
   wire \shift_register0/n34 ;
   wire \shift_register0/n33 ;
   wire \shift_register0/n32 ;
   wire \shift_register0/n31 ;
   wire \shift_register0/n30 ;
   wire \shift_register0/n29 ;
   wire \shift_register0/n28 ;
   wire \shift_register0/n27 ;
   wire \shift_register0/n26 ;
   wire \shift_register0/n25 ;
   wire \shift_register0/n24 ;
   wire \shift_register0/n23 ;
   wire \shift_register0/n22 ;
   wire \shift_register0/n21 ;
   wire \shift_register0/n20 ;
   wire \shift_register0/n19 ;
   wire \shift_register0/n18 ;
   wire \shift_register0/n17 ;
   wire \shift_register0/n16 ;
   wire \shift_register0/n15 ;
   wire \shift_register0/n14 ;
   wire \shift_register0/n13 ;
   wire \shift_register0/n12 ;
   wire \shift_register0/n11 ;
   wire \shift_register0/n10 ;
   wire \shift_register0/n9 ;
   wire \shift_register0/n8 ;
   wire \shift_register0/n5 ;
   wire \shift_register0/n4 ;
   wire \shift_register0/n2 ;
   wire \shift_register0/shiftnextbit ;
   wire \shift_register0/shift_register[0] ;
   wire \shift_register0/shift_register[1] ;
   wire \shift_register0/shift_register[2] ;
   wire \shift_register0/shift_register[3] ;
   wire \shift_register0/shift_register[4] ;
   wire \shift_register0/shift_register[5] ;
   wire \shift_register0/shift_register[6] ;
   wire \shift_register0/shift_register[7] ;
   wire \shift_register0/shift_register[8] ;
   wire \shift_register0/shift_register[9] ;
   wire \shift_register0/shift_register[10] ;
   wire \shift_register0/shift_register[11] ;
   wire \shift_register0/shift_register[12] ;
   wire \shift_register0/shift_register[13] ;
   wire \shift_register0/shift_register[14] ;
   wire \shift_register0/shift_register[15] ;
   wire \shift_register0/shift_register[16] ;
   wire \shift_register0/shift_register[17] ;
   wire \shift_register0/shift_register[18] ;
   wire \shift_register0/shift_register[19] ;
   wire \shift_register0/shift_register[20] ;
   wire \shift_register0/shift_register[21] ;
   wire \shift_register0/shift_register[22] ;
   wire \shift_register0/shift_register[23] ;
   wire \shift_register0/shift_register[24] ;
   wire \shift_register0/shift_register[25] ;
   wire \shift_register0/shift_register[26] ;
   wire \shift_register0/shift_register[27] ;
   wire \shift_register0/shift_register[28] ;
   wire \shift_register0/shift_register[29] ;
   wire \shift_register0/shift_register[30] ;
   wire \shift_register0/shift_register[31] ;
   wire n1;
   wire n3;
   wire n19;
   wire n41;
   wire n42;
   wire n43;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire [31:0] data_out_shift_reg;
   wire restart_mem;
   wire fifo_wr;
   wire fifo_rd;
   wire [7:0] data_out_to_data_in;
   wire fifo_empty;

   assign ROM_addr[2] = 1'b0 ;
   assign ROM_addr[3] = 1'b0 ;
   assign ROM_re = 1'b1 ;
   assign ROM_ce = 1'b1 ;

   Spare_1 myspare__spr_1 ();
   fifo fifo0 (.data_in(ROM_data), 
	.wr(fifo_wr), 
	.rd(fifo_rd), 
	.restart(restart_mem), 
	.reset_n(reset_n), 
	.clk_mem(clk_mem), 
	.clk(clk), 
	.data_out(data_out_to_data_in), 
	.fifo_empty(fifo_empty));
   DFFARX1 \mem_to_fifo_sm0/fifo_wr_reg  (.RSTB(reset_n), 
	.Q(fifo_wr), 
	.D(\mem_to_fifo_sm0/n28 ), 
	.CLK(clk_mem));
   DFFX1 \mem_to_fifo_sm0/ROM_addr_reg[0]  (.Q(ROM_addr[0]), 
	.D(\mem_to_fifo_sm0/n30 ), 
	.CLK(clk_mem));
   DFFX1 \mem_to_fifo_sm0/ROM_addr_reg[1]  (.Q(ROM_addr[1]), 
	.D(\mem_to_fifo_sm0/n29 ), 
	.CLK(clk_mem));
   DFFASX1 \mem_to_fifo_sm0/state_reg[0]  (.SETB(reset_n), 
	.QN(\mem_to_fifo_sm0/n6 ), 
	.Q(\mem_to_fifo_sm0/state[0] ), 
	.D(\mem_to_fifo_sm0/n33 ), 
	.CLK(clk_mem));
   DFFARX1 \mem_to_fifo_sm0/state_reg[1]  (.RSTB(reset_n), 
	.QN(\mem_to_fifo_sm0/n5 ), 
	.Q(\mem_to_fifo_sm0/state[1] ), 
	.D(\mem_to_fifo_sm0/n32 ), 
	.CLK(clk_mem));
   DFFX1 \shift_register_sm0/data_out_reg[0]  (.Q(data_out_shift_reg[0]), 
	.D(\shift_register_sm0/n70 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[1]  (.Q(data_out_shift_reg[1]), 
	.D(\shift_register_sm0/n72 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[2]  (.Q(data_out_shift_reg[2]), 
	.D(\shift_register_sm0/n74 ), 
	.CLK(clk));
   DFFARX1 \shift_register_sm0/fifo_rd_reg  (.RSTB(reset_n), 
	.Q(fifo_rd), 
	.D(\shift_register_sm0/n135 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[0]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[0] ), 
	.D(\shift_register0/n9 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[31]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[31] ), 
	.D(\shift_register0/n10 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[24]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[24] ), 
	.D(\shift_register0/n17 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[1]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[1] ), 
	.D(\shift_register0/n40 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[2]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[2] ), 
	.D(\shift_register0/n39 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[3]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[3] ), 
	.D(\shift_register0/n38 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[4]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[4] ), 
	.D(\shift_register0/n37 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[5]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[5] ), 
	.D(\shift_register0/n36 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[6]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[6] ), 
	.D(\shift_register0/n35 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[7]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[7] ), 
	.D(\shift_register0/n34 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[8]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[8] ), 
	.D(\shift_register0/n33 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[9]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[9] ), 
	.D(\shift_register0/n32 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[10]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[10] ), 
	.D(\shift_register0/n31 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[11]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[11] ), 
	.D(\shift_register0/n30 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[12]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[12] ), 
	.D(\shift_register0/n29 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[13]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[13] ), 
	.D(\shift_register0/n28 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[14]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[14] ), 
	.D(\shift_register0/n27 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[15]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[15] ), 
	.D(\shift_register0/n26 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[16]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[16] ), 
	.D(\shift_register0/n25 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[17]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[17] ), 
	.D(\shift_register0/n24 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[18]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[18] ), 
	.D(\shift_register0/n23 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[19]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[19] ), 
	.D(\shift_register0/n22 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[20]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[20] ), 
	.D(\shift_register0/n21 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[21]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[21] ), 
	.D(\shift_register0/n20 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[22]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[22] ), 
	.D(\shift_register0/n19 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[23]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[23] ), 
	.D(\shift_register0/n18 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[25]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[25] ), 
	.D(\shift_register0/n16 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[26]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[26] ), 
	.D(\shift_register0/n15 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[27]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[27] ), 
	.D(\shift_register0/n14 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[28]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[28] ), 
	.D(\shift_register0/n13 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[29]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[29] ), 
	.D(\shift_register0/n12 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shift_register_reg[30]  (.RSTB(reset_n), 
	.Q(\shift_register0/shift_register[30] ), 
	.D(\shift_register0/n11 ), 
	.CLK(clk));
   DFFARX1 \counter_sm0/state_reg[2]  (.RSTB(reset_n), 
	.QN(\counter_sm0/n5 ), 
	.Q(\counter_sm0/state[2] ), 
	.D(\counter_sm0/n31 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/shiftnextbit_reg  (.RSTB(reset_n), 
	.QN(n3), 
	.Q(\shift_register0/shiftnextbit ), 
	.D(\shift_register0/n41 ), 
	.CLK(clk));
   DFFASX1 \counter_sm0/state_reg[0]  (.SETB(reset_n), 
	.QN(\counter_sm0/n8 ), 
	.Q(\counter_sm0/state[0] ), 
	.D(\counter_sm0/n33 ), 
	.CLK(clk));
   DFFARX1 \shift_register0/out_reg  (.RSTB(reset_n), 
	.Q(LED), 
	.D(\shift_register0/n8 ), 
	.CLK(clk));
   DFFARX1 \shift_register_sm0/state_reg[1]  (.RSTB(reset_n), 
	.QN(\shift_register_sm0/n19 ), 
	.Q(\shift_register_sm0/state[1] ), 
	.D(\shift_register_sm0/n137 ), 
	.CLK(clk));
   DFFARX1 \counter_sm0/state_reg[1]  (.RSTB(reset_n), 
	.QN(\counter_sm0/n7 ), 
	.Q(\counter_sm0/state[1] ), 
	.D(\counter_sm0/n32 ), 
	.CLK(clk));
   DFFARX1 \shift_register_sm0/state_reg[3]  (.RSTB(reset_n), 
	.QN(\shift_register_sm0/n15 ), 
	.Q(\shift_register_sm0/state[3] ), 
	.D(\shift_register_sm0/n138 ), 
	.CLK(clk));
   DFFARX1 \shift_register_sm0/state_reg[2]  (.RSTB(reset_n), 
	.Q(\shift_register_sm0/state[2] ), 
	.D(\shift_register_sm0/n136 ), 
	.CLK(clk));
   DFFASX1 \shift_register_sm0/state_reg[0]  (.SETB(reset_n), 
	.QN(\shift_register_sm0/n20 ), 
	.Q(\shift_register_sm0/state[0] ), 
	.D(\shift_register_sm0/n139 ), 
	.CLK(clk));
   MUX21X1 \shift_register_sm0/U142  (.S(\shift_register_sm0/state[3] ), 
	.Q(\shift_register_sm0/n143 ), 
	.IN2(n71), 
	.IN1(\shift_register_sm0/n23 ));
   OR2X1 \shift_register_sm0/U144  (.Q(\shift_register_sm0/n145 ), 
	.IN2(\shift_register_sm0/n143 ), 
	.IN1(\shift_register_sm0/state[0] ));
   XOR2X1 \shift_register_sm0/U139  (.Q(\shift_register_sm0/n140 ), 
	.IN2(\divider_even0/rout ), 
	.IN1(\shift_register_sm0/state[0] ));
   MUX21X1 \shift_register_sm0/U143  (.S(\shift_register_sm0/state[3] ), 
	.Q(\shift_register_sm0/n144 ), 
	.IN2(\shift_register_sm0/n141 ), 
	.IN1(\shift_register_sm0/state[0] ));
   OR2X1 \shift_register_sm0/U140  (.Q(\shift_register_sm0/n141 ), 
	.IN2(\shift_register_sm0/state[0] ), 
	.IN1(\shift_register_sm0/n23 ));
   MUX21X1 \shift_register_sm0/U145  (.S(\shift_register_sm0/state[1] ), 
	.Q(\shift_register_sm0/n146 ), 
	.IN2(\shift_register_sm0/n145 ), 
	.IN1(\shift_register_sm0/n144 ));
   MUX21X1 \shift_register_sm0/U141  (.S(\shift_register_sm0/state[3] ), 
	.Q(\shift_register_sm0/n142 ), 
	.IN2(\shift_register_sm0/n140 ), 
	.IN1(\shift_register_sm0/n141 ));
   MUX21X1 \shift_register_sm0/U146  (.S(\shift_register_sm0/state[2] ), 
	.Q(\shift_register_sm0/N89 ), 
	.IN2(\shift_register_sm0/n142 ), 
	.IN1(\shift_register_sm0/n146 ));
   DFFSSRX1 \shift_register_sm0/load_sr_reg  (.SETB(n1), 
	.RSTB(n43), 
	.QN(n55), 
	.Q(load_sr), 
	.D(1'b1), 
	.CLK(clk));
   DFFX1 \divider_even0/rout_reg  (.QN(n71), 
	.Q(\divider_even0/rout ), 
	.D(\divider_even0/N4 ), 
	.CLK(clk));
   DFFX1 \counter_sm0/restart_reg  (.QN(n66), 
	.Q(restart), 
	.D(\counter_sm0/n29 ), 
	.CLK(clk));
   DFFX1 \counter_sm0/restart_mem_reg  (.Q(restart_mem), 
	.D(\counter_sm0/n30 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/shift_sr_reg  (.Q(shift_sr), 
	.D(\shift_register_sm0/n134 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[7]  (.Q(\shift_register_sm0/out[7] ), 
	.D(\shift_register_sm0/n85 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[6]  (.Q(\shift_register_sm0/out[6] ), 
	.D(\shift_register_sm0/n83 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[5]  (.Q(\shift_register_sm0/out[5] ), 
	.D(\shift_register_sm0/n81 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[4]  (.Q(\shift_register_sm0/out[4] ), 
	.D(\shift_register_sm0/n79 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[3]  (.Q(\shift_register_sm0/out[3] ), 
	.D(\shift_register_sm0/n77 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[2]  (.Q(\shift_register_sm0/out[2] ), 
	.D(\shift_register_sm0/n75 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[1]  (.Q(\shift_register_sm0/out[1] ), 
	.D(\shift_register_sm0/n73 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[0]  (.Q(\shift_register_sm0/out[0] ), 
	.D(\shift_register_sm0/n71 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[31]  (.Q(\shift_register_sm0/out[31] ), 
	.D(\shift_register_sm0/n133 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[30]  (.Q(\shift_register_sm0/out[30] ), 
	.D(\shift_register_sm0/n131 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[29]  (.Q(\shift_register_sm0/out[29] ), 
	.D(\shift_register_sm0/n129 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[28]  (.Q(\shift_register_sm0/out[28] ), 
	.D(\shift_register_sm0/n127 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[27]  (.Q(\shift_register_sm0/out[27] ), 
	.D(\shift_register_sm0/n125 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[26]  (.Q(\shift_register_sm0/out[26] ), 
	.D(\shift_register_sm0/n123 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[25]  (.Q(\shift_register_sm0/out[25] ), 
	.D(\shift_register_sm0/n121 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[24]  (.Q(\shift_register_sm0/out[24] ), 
	.D(\shift_register_sm0/n119 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[23]  (.Q(\shift_register_sm0/out[23] ), 
	.D(\shift_register_sm0/n117 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[22]  (.Q(\shift_register_sm0/out[22] ), 
	.D(\shift_register_sm0/n115 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[21]  (.Q(\shift_register_sm0/out[21] ), 
	.D(\shift_register_sm0/n113 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[20]  (.Q(\shift_register_sm0/out[20] ), 
	.D(\shift_register_sm0/n111 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[19]  (.Q(\shift_register_sm0/out[19] ), 
	.D(\shift_register_sm0/n109 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[18]  (.Q(\shift_register_sm0/out[18] ), 
	.D(\shift_register_sm0/n107 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[17]  (.Q(\shift_register_sm0/out[17] ), 
	.D(\shift_register_sm0/n105 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[16]  (.Q(\shift_register_sm0/out[16] ), 
	.D(\shift_register_sm0/n103 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[15]  (.Q(\shift_register_sm0/out[15] ), 
	.D(\shift_register_sm0/n101 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[14]  (.Q(\shift_register_sm0/out[14] ), 
	.D(\shift_register_sm0/n99 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[13]  (.Q(\shift_register_sm0/out[13] ), 
	.D(\shift_register_sm0/n97 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[12]  (.Q(\shift_register_sm0/out[12] ), 
	.D(\shift_register_sm0/n95 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[11]  (.Q(\shift_register_sm0/out[11] ), 
	.D(\shift_register_sm0/n93 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[10]  (.Q(\shift_register_sm0/out[10] ), 
	.D(\shift_register_sm0/n91 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[9]  (.Q(\shift_register_sm0/out[9] ), 
	.D(\shift_register_sm0/n89 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/out_reg[8]  (.Q(\shift_register_sm0/out[8] ), 
	.D(\shift_register_sm0/n87 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[31]  (.Q(data_out_shift_reg[31]), 
	.D(\shift_register_sm0/n132 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[30]  (.Q(data_out_shift_reg[30]), 
	.D(\shift_register_sm0/n130 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[29]  (.Q(data_out_shift_reg[29]), 
	.D(\shift_register_sm0/n128 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[28]  (.Q(data_out_shift_reg[28]), 
	.D(\shift_register_sm0/n126 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[27]  (.Q(data_out_shift_reg[27]), 
	.D(\shift_register_sm0/n124 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[26]  (.Q(data_out_shift_reg[26]), 
	.D(\shift_register_sm0/n122 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[25]  (.Q(data_out_shift_reg[25]), 
	.D(\shift_register_sm0/n120 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[24]  (.Q(data_out_shift_reg[24]), 
	.D(\shift_register_sm0/n118 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[23]  (.Q(data_out_shift_reg[23]), 
	.D(\shift_register_sm0/n116 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[22]  (.Q(data_out_shift_reg[22]), 
	.D(\shift_register_sm0/n114 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[21]  (.Q(data_out_shift_reg[21]), 
	.D(\shift_register_sm0/n112 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[20]  (.Q(data_out_shift_reg[20]), 
	.D(\shift_register_sm0/n110 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[19]  (.Q(data_out_shift_reg[19]), 
	.D(\shift_register_sm0/n108 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[18]  (.Q(data_out_shift_reg[18]), 
	.D(\shift_register_sm0/n106 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[17]  (.Q(data_out_shift_reg[17]), 
	.D(\shift_register_sm0/n104 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[16]  (.Q(data_out_shift_reg[16]), 
	.D(\shift_register_sm0/n102 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[15]  (.Q(data_out_shift_reg[15]), 
	.D(\shift_register_sm0/n100 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[14]  (.Q(data_out_shift_reg[14]), 
	.D(\shift_register_sm0/n98 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[13]  (.Q(data_out_shift_reg[13]), 
	.D(\shift_register_sm0/n96 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[12]  (.Q(data_out_shift_reg[12]), 
	.D(\shift_register_sm0/n94 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[11]  (.Q(data_out_shift_reg[11]), 
	.D(\shift_register_sm0/n92 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[10]  (.Q(data_out_shift_reg[10]), 
	.D(\shift_register_sm0/n90 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[9]  (.Q(data_out_shift_reg[9]), 
	.D(\shift_register_sm0/n88 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[8]  (.Q(data_out_shift_reg[8]), 
	.D(\shift_register_sm0/n86 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[7]  (.Q(data_out_shift_reg[7]), 
	.D(\shift_register_sm0/n84 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[6]  (.Q(data_out_shift_reg[6]), 
	.D(\shift_register_sm0/n82 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[5]  (.Q(data_out_shift_reg[5]), 
	.D(\shift_register_sm0/n80 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[4]  (.Q(data_out_shift_reg[4]), 
	.D(\shift_register_sm0/n78 ), 
	.CLK(clk));
   DFFX1 \shift_register_sm0/data_out_reg[3]  (.Q(data_out_shift_reg[3]), 
	.D(\shift_register_sm0/n76 ), 
	.CLK(clk));
   DFFARX1 \mem_to_fifo_sm0/state_reg[2]  (.RSTB(reset_n), 
	.QN(n73), 
	.Q(\mem_to_fifo_sm0/state[2] ), 
	.D(\mem_to_fifo_sm0/n31 ), 
	.CLK(clk_mem));
   AND2X1 U3 (.Q(n1), 
	.IN2(\shift_register_sm0/n32 ), 
	.IN1(n77));
   INVX0 U5 (.QN(n43), 
	.IN(\shift_register_sm0/n25 ));
   INVX0 U16 (.QN(n19), 
	.IN(\shift_register_sm0/n25 ));
   INVX0 U41 (.QN(n56), 
	.IN(\shift_register_sm0/n31 ));
   NOR2X0 U42 (.QN(\shift_register0/n2 ), 
	.IN2(load_sr), 
	.IN1(n74));
   INVX0 U44 (.QN(n41), 
	.IN(\shift_register_sm0/n25 ));
   INVX0 U45 (.QN(n42), 
	.IN(\shift_register_sm0/n25 ));
   INVX0 U56 (.QN(n58), 
	.IN(\shift_register_sm0/n26 ));
   INVX0 U57 (.QN(n57), 
	.IN(\shift_register_sm0/n29 ));
   INVX0 U58 (.QN(n61), 
	.IN(\shift_register_sm0/n33 ));
   INVX0 U60 (.QN(n82), 
	.IN(\shift_register_sm0/n62 ));
   INVX0 U61 (.QN(n79), 
	.IN(\shift_register_sm0/n48 ));
   INVX0 U62 (.QN(n69), 
	.IN(\counter_sm0/n16 ));
   NAND2X0 U63 (.QN(\shift_register_sm0/n31 ), 
	.IN2(\shift_register_sm0/n27 ), 
	.IN1(n81));
   INVX0 U64 (.QN(n67), 
	.IN(\mem_to_fifo_sm0/N43 ));
   NAND2X0 U65 (.QN(\shift_register_sm0/n29 ), 
	.IN2(\shift_register_sm0/n27 ), 
	.IN1(\shift_register_sm0/n30 ));
   NAND2X0 U66 (.QN(\shift_register_sm0/n26 ), 
	.IN2(n78), 
	.IN1(\shift_register_sm0/n27 ));
   INVX0 U67 (.QN(n78), 
	.IN(\shift_register_sm0/n28 ));
   NAND2X0 U68 (.QN(\shift_register_sm0/n25 ), 
	.IN2(\shift_register_sm0/n40 ), 
	.IN1(\shift_register_sm0/n32 ));
   NAND3X0 U69 (.QN(\shift_register_sm0/n33 ), 
	.IN3(n82), 
	.IN2(n71), 
	.IN1(\shift_register_sm0/n32 ));
   NAND2X0 U70 (.QN(\shift_register_sm0/n62 ), 
	.IN2(\shift_register_sm0/n67 ), 
	.IN1(\shift_register_sm0/n56 ));
   NAND2X0 U71 (.QN(\counter_sm0/n16 ), 
	.IN2(\counter_sm0/n12 ), 
	.IN1(\counter_sm0/n14 ));
   NAND3X0 U72 (.QN(\shift_register_sm0/n48 ), 
	.IN3(\shift_register_sm0/n59 ), 
	.IN2(\shift_register_sm0/n28 ), 
	.IN1(\shift_register_sm0/n66 ));
   AND3X1 U73 (.Q(\shift_register_sm0/n52 ), 
	.IN3(n76), 
	.IN2(\shift_register_sm0/n38 ), 
	.IN1(\shift_register_sm0/n37 ));
   AND2X1 U74 (.Q(\shift_register_sm0/n45 ), 
	.IN2(\shift_register_sm0/n62 ), 
	.IN1(\shift_register_sm0/n44 ));
   INVX0 U75 (.QN(n64), 
	.IN(\counter_sm0/n22 ));
   NAND2X0 U76 (.QN(\shift_register_sm0/n46 ), 
	.IN2(\shift_register_sm0/n23 ), 
	.IN1(\shift_register_sm0/n48 ));
   INVX0 U77 (.QN(n80), 
	.IN(\shift_register_sm0/n55 ));
   INVX0 U78 (.QN(n76), 
	.IN(\shift_register_sm0/n35 ));
   INVX0 U79 (.QN(n74), 
	.IN(\shift_register0/n4 ));
   INVX0 U80 (.QN(n81), 
	.IN(\shift_register_sm0/n66 ));
   AND2X1 U81 (.Q(\shift_register_sm0/n27 ), 
	.IN2(\shift_register_sm0/n23 ), 
	.IN1(\shift_register_sm0/n32 ));
   INVX0 U82 (.QN(n54), 
	.IN(n55));
   NAND3X0 U83 (.QN(\mem_to_fifo_sm0/N43 ), 
	.IN3(\mem_to_fifo_sm0/n23 ), 
	.IN2(\mem_to_fifo_sm0/n7 ), 
	.IN1(\mem_to_fifo_sm0/n20 ));
   INVX0 U84 (.QN(n83), 
	.IN(\shift_register_sm0/n47 ));
   INVX0 U85 (.QN(n62), 
	.IN(\mem_to_fifo_sm0/n14 ));
   INVX0 U86 (.QN(n77), 
	.IN(\shift_register_sm0/n37 ));
   AND3X1 U87 (.Q(\mem_to_fifo_sm0/n23 ), 
	.IN3(\mem_to_fifo_sm0/n21 ), 
	.IN2(\mem_to_fifo_sm0/n10 ), 
	.IN1(\mem_to_fifo_sm0/n12 ));
   NOR2X0 U88 (.QN(\mem_to_fifo_sm0/n20 ), 
	.IN2(n72), 
	.IN1(\mem_to_fifo_sm0/n15 ));
   INVX0 U89 (.QN(n72), 
	.IN(\mem_to_fifo_sm0/n17 ));
   NAND2X0 U90 (.QN(\mem_to_fifo_sm0/n15 ), 
	.IN2(\mem_to_fifo_sm0/n18 ), 
	.IN1(\mem_to_fifo_sm0/n24 ));
   AO22X1 U91 (.Q(\counter_sm0/n30 ), 
	.IN4(\counter_sm0/n16 ), 
	.IN3(n63), 
	.IN2(\counter_sm0/n15 ), 
	.IN1(restart_mem));
   INVX0 U92 (.QN(n63), 
	.IN(\counter_sm0/n15 ));
   NAND2X0 U93 (.QN(\counter_sm0/n15 ), 
	.IN2(reset_n), 
	.IN1(\counter_sm0/n17 ));
   NAND3X0 U94 (.QN(\counter_sm0/n17 ), 
	.IN3(n69), 
	.IN2(\counter_sm0/n13 ), 
	.IN1(\counter_sm0/n18 ));
   NOR2X0 U95 (.QN(\shift_register_sm0/n32 ), 
	.IN2(restart), 
	.IN1(\shift_register_sm0/n24 ));
   INVX0 U96 (.QN(\shift_register_sm0/n24 ), 
	.IN(reset_n));
   NAND4X0 U97 (.QN(\counter_sm0/n22 ), 
	.IN4(\counter_sm0/n20 ), 
	.IN3(\counter_sm0/n25 ), 
	.IN2(\counter_sm0/n24 ), 
	.IN1(n69));
   NAND2X0 U98 (.QN(\counter_sm0/n25 ), 
	.IN2(\counter_sm0/n8 ), 
	.IN1(n65));
   OR2X1 U99 (.Q(\counter_sm0/n24 ), 
	.IN2(\counter_sm0/n13 ), 
	.IN1(n65));
   NOR2X0 U100 (.QN(\shift_register_sm0/n49 ), 
	.IN2(restart), 
	.IN1(\shift_register_sm0/N89 ));
   NOR2X0 U101 (.QN(\shift_register_sm0/n56 ), 
	.IN2(\shift_register_sm0/state[0] ), 
	.IN1(\shift_register_sm0/n19 ));
   NAND2X0 U102 (.QN(\shift_register_sm0/n55 ), 
	.IN2(\shift_register_sm0/n19 ), 
	.IN1(\shift_register_sm0/state[2] ));
   NOR2X0 U103 (.QN(\shift_register_sm0/n67 ), 
	.IN2(\shift_register_sm0/state[2] ), 
	.IN1(\shift_register_sm0/n15 ));
   AND3X1 U104 (.Q(\shift_register_sm0/n40 ), 
	.IN3(\shift_register_sm0/state[1] ), 
	.IN2(\shift_register_sm0/n67 ), 
	.IN1(\shift_register_sm0/state[0] ));
   NAND3X0 U105 (.QN(\shift_register_sm0/n37 ), 
	.IN3(n80), 
	.IN2(\shift_register_sm0/state[3] ), 
	.IN1(\shift_register_sm0/state[0] ));
   AND3X1 U106 (.Q(\shift_register_sm0/n30 ), 
	.IN3(\shift_register_sm0/n56 ), 
	.IN2(\shift_register_sm0/n15 ), 
	.IN1(\shift_register_sm0/state[2] ));
   NAND3X0 U107 (.QN(\counter_sm0/n14 ), 
	.IN3(\counter_sm0/state[1] ), 
	.IN2(\counter_sm0/n5 ), 
	.IN1(\counter_sm0/n8 ));
   NAND2X0 U108 (.QN(\shift_register_sm0/n35 ), 
	.IN2(\shift_register_sm0/n69 ), 
	.IN1(\shift_register_sm0/n61 ));
   NAND3X0 U109 (.QN(\shift_register_sm0/n69 ), 
	.IN3(n80), 
	.IN2(\shift_register_sm0/n20 ), 
	.IN1(\shift_register_sm0/state[3] ));
   NOR2X0 U110 (.QN(\shift_register_sm0/n50 ), 
	.IN2(restart), 
	.IN1(\shift_register_sm0/n49 ));
   NAND4X0 U111 (.QN(\shift_register_sm0/n38 ), 
	.IN4(\shift_register_sm0/state[3] ), 
	.IN3(\shift_register_sm0/state[0] ), 
	.IN2(\shift_register_sm0/state[1] ), 
	.IN1(\shift_register_sm0/state[2] ));
   OR3X1 U112 (.Q(\shift_register0/n4 ), 
	.IN3(n3), 
	.IN2(shift_sr), 
	.IN1(load_sr));
   NAND3X0 U113 (.QN(\shift_register_sm0/n28 ), 
	.IN3(n80), 
	.IN2(\shift_register_sm0/n15 ), 
	.IN1(\shift_register_sm0/n20 ));
   NAND3X0 U114 (.QN(\shift_register_sm0/n66 ), 
	.IN3(\shift_register_sm0/n67 ), 
	.IN2(\shift_register_sm0/n19 ), 
	.IN1(\shift_register_sm0/n20 ));
   AO222X1 U115 (.Q(\shift_register0/n18 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[23]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[23] ), 
	.IN2(\shift_register0/shift_register[24] ), 
	.IN1(n74));
   AO222X1 U116 (.Q(\shift_register0/n11 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[30]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[30] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[31] ));
   AO222X1 U117 (.Q(\shift_register0/n12 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[29]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[29] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[30] ));
   AO222X1 U118 (.Q(\shift_register0/n13 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[28]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[28] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[29] ));
   AO222X1 U119 (.Q(\shift_register0/n14 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[27]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[27] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[28] ));
   AO222X1 U120 (.Q(\shift_register0/n15 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[26]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[26] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[27] ));
   AO222X1 U121 (.Q(\shift_register0/n16 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[25]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[25] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[26] ));
   AO222X1 U122 (.Q(\shift_register0/n17 ), 
	.IN6(data_out_shift_reg[24]), 
	.IN5(load_sr), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[24] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[25] ));
   AO222X1 U123 (.Q(\shift_register0/n37 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[4]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[4] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[5] ));
   AO222X1 U124 (.Q(\shift_register0/n38 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[3]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[3] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[4] ));
   AO222X1 U125 (.Q(\shift_register0/n39 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[2]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[2] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[3] ));
   AO222X1 U126 (.Q(\shift_register0/n9 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[0]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[0] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[1] ));
   AO222X1 U127 (.Q(\shift_register0/n25 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[16]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[16] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[17] ));
   AO222X1 U128 (.Q(\shift_register0/n26 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[15]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[15] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[16] ));
   AO222X1 U129 (.Q(\shift_register0/n27 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[14]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[14] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[15] ));
   AO222X1 U130 (.Q(\shift_register0/n28 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[13]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[13] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[14] ));
   AO222X1 U131 (.Q(\shift_register0/n29 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[12]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[12] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[13] ));
   AO222X1 U132 (.Q(\shift_register0/n30 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[11]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[11] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[12] ));
   AO222X1 U133 (.Q(\shift_register0/n31 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[10]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[10] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[11] ));
   AO222X1 U134 (.Q(\shift_register0/n32 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[9]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[9] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[10] ));
   AO222X1 U135 (.Q(\shift_register0/n33 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[8]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[8] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[9] ));
   AO222X1 U136 (.Q(\shift_register0/n34 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[7]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[7] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[8] ));
   AO222X1 U137 (.Q(\shift_register0/n35 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[6]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[6] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[7] ));
   AO222X1 U138 (.Q(\shift_register0/n36 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[5]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[5] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[6] ));
   AO222X1 U139 (.Q(\shift_register0/n40 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[1]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[1] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[2] ));
   AO222X1 U140 (.Q(\shift_register0/n19 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[22]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[22] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[23] ));
   AO222X1 U141 (.Q(\shift_register0/n20 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[21]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[21] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[22] ));
   AO222X1 U142 (.Q(\shift_register0/n21 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[20]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[20] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[21] ));
   AO222X1 U143 (.Q(\shift_register0/n22 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[19]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[19] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[20] ));
   AO222X1 U144 (.Q(\shift_register0/n23 ), 
	.IN6(n54), 
	.IN5(data_out_shift_reg[18]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[18] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[19] ));
   AO222X1 U145 (.Q(\shift_register0/n24 ), 
	.IN6(load_sr), 
	.IN5(data_out_shift_reg[17]), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[17] ), 
	.IN2(n74), 
	.IN1(\shift_register0/shift_register[18] ));
   AO22X1 U146 (.Q(\shift_register_sm0/n136 ), 
	.IN4(\shift_register_sm0/n51 ), 
	.IN3(\shift_register_sm0/n50 ), 
	.IN2(\shift_register_sm0/state[2] ), 
	.IN1(\shift_register_sm0/n49 ));
   NAND4X0 U147 (.QN(\shift_register_sm0/n51 ), 
	.IN4(\shift_register_sm0/n55 ), 
	.IN3(\shift_register_sm0/n54 ), 
	.IN2(\shift_register_sm0/n53 ), 
	.IN1(\shift_register_sm0/n52 ));
   OR3X1 U148 (.Q(\shift_register_sm0/n53 ), 
	.IN3(\shift_register_sm0/n47 ), 
	.IN2(\shift_register_sm0/state[2] ), 
	.IN1(\shift_register_sm0/n19 ));
   NOR2X0 U149 (.QN(\shift_register_sm0/n54 ), 
	.IN2(\shift_register_sm0/n30 ), 
	.IN1(\shift_register_sm0/n40 ));
   AO22X1 U150 (.Q(\shift_register_sm0/n132 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[31]), 
	.IN2(n43), 
	.IN1(\shift_register_sm0/out[31] ));
   AO22X1 U151 (.Q(\shift_register_sm0/n130 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[30]), 
	.IN2(n43), 
	.IN1(\shift_register_sm0/out[30] ));
   AO22X1 U152 (.Q(\shift_register_sm0/n128 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[29]), 
	.IN2(n19), 
	.IN1(\shift_register_sm0/out[29] ));
   AO22X1 U153 (.Q(\shift_register_sm0/n126 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[28]), 
	.IN2(n19), 
	.IN1(\shift_register_sm0/out[28] ));
   AO22X1 U154 (.Q(\shift_register_sm0/n124 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[27]), 
	.IN2(n19), 
	.IN1(\shift_register_sm0/out[27] ));
   AO22X1 U155 (.Q(\shift_register_sm0/n122 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[26]), 
	.IN2(n19), 
	.IN1(\shift_register_sm0/out[26] ));
   AO22X1 U156 (.Q(\shift_register_sm0/n120 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[25]), 
	.IN2(n19), 
	.IN1(\shift_register_sm0/out[25] ));
   AO22X1 U157 (.Q(\shift_register_sm0/n118 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[24]), 
	.IN2(n19), 
	.IN1(\shift_register_sm0/out[24] ));
   AO22X1 U158 (.Q(\shift_register_sm0/n116 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[23]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[23] ));
   AO22X1 U159 (.Q(\shift_register_sm0/n114 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[22]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[22] ));
   AO22X1 U160 (.Q(\shift_register_sm0/n112 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[21]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[21] ));
   AO22X1 U161 (.Q(\shift_register_sm0/n110 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[20]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[20] ));
   AO22X1 U162 (.Q(\shift_register_sm0/n108 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[19]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[19] ));
   AO22X1 U163 (.Q(\shift_register_sm0/n106 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[18]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[18] ));
   AO22X1 U164 (.Q(\shift_register_sm0/n104 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[17]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[17] ));
   AO22X1 U165 (.Q(\shift_register_sm0/n102 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[16]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[16] ));
   AO22X1 U166 (.Q(\shift_register_sm0/n100 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[15]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[15] ));
   AO22X1 U167 (.Q(\shift_register_sm0/n98 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[14]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[14] ));
   AO22X1 U168 (.Q(\shift_register_sm0/n96 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[13]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[13] ));
   AO22X1 U169 (.Q(\shift_register_sm0/n94 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[12]), 
	.IN2(n41), 
	.IN1(\shift_register_sm0/out[12] ));
   AO22X1 U170 (.Q(\shift_register_sm0/n92 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[11]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[11] ));
   AO22X1 U171 (.Q(\shift_register_sm0/n90 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[10]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[10] ));
   AO22X1 U172 (.Q(\shift_register_sm0/n88 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[9]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[9] ));
   AO22X1 U173 (.Q(\shift_register_sm0/n86 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[8]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[8] ));
   AO22X1 U174 (.Q(\shift_register_sm0/n84 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[7]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[7] ));
   AO22X1 U175 (.Q(\shift_register_sm0/n82 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[6]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[6] ));
   AO22X1 U176 (.Q(\shift_register_sm0/n80 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[5]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[5] ));
   AO22X1 U177 (.Q(\shift_register_sm0/n78 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[4]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[4] ));
   AO22X1 U178 (.Q(\shift_register_sm0/n76 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[3]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[3] ));
   AO22X1 U179 (.Q(\shift_register_sm0/n74 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[2]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[2] ));
   AO22X1 U180 (.Q(\shift_register_sm0/n72 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[1]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[1] ));
   AO22X1 U181 (.Q(\shift_register_sm0/n70 ), 
	.IN4(\shift_register_sm0/n25 ), 
	.IN3(data_out_shift_reg[0]), 
	.IN2(n42), 
	.IN1(\shift_register_sm0/out[0] ));
   AO22X1 U182 (.Q(\shift_register_sm0/n101 ), 
	.IN4(\shift_register_sm0/n29 ), 
	.IN3(\shift_register_sm0/out[15] ), 
	.IN2(data_out_to_data_in[7]), 
	.IN1(n57));
   AO22X1 U183 (.Q(\shift_register_sm0/n99 ), 
	.IN4(\shift_register_sm0/n29 ), 
	.IN3(\shift_register_sm0/out[14] ), 
	.IN2(data_out_to_data_in[6]), 
	.IN1(n57));
   AO22X1 U184 (.Q(\shift_register_sm0/n97 ), 
	.IN4(\shift_register_sm0/n29 ), 
	.IN3(\shift_register_sm0/out[13] ), 
	.IN2(data_out_to_data_in[5]), 
	.IN1(n57));
   AO22X1 U185 (.Q(\shift_register_sm0/n95 ), 
	.IN4(\shift_register_sm0/n29 ), 
	.IN3(\shift_register_sm0/out[12] ), 
	.IN2(data_out_to_data_in[4]), 
	.IN1(n57));
   AO22X1 U186 (.Q(\shift_register_sm0/n93 ), 
	.IN4(\shift_register_sm0/n29 ), 
	.IN3(\shift_register_sm0/out[11] ), 
	.IN2(data_out_to_data_in[3]), 
	.IN1(n57));
   AO22X1 U187 (.Q(\shift_register_sm0/n91 ), 
	.IN4(\shift_register_sm0/n29 ), 
	.IN3(\shift_register_sm0/out[10] ), 
	.IN2(data_out_to_data_in[2]), 
	.IN1(n57));
   AO22X1 U188 (.Q(\shift_register_sm0/n89 ), 
	.IN4(\shift_register_sm0/n29 ), 
	.IN3(\shift_register_sm0/out[9] ), 
	.IN2(data_out_to_data_in[1]), 
	.IN1(n57));
   AO22X1 U189 (.Q(\shift_register_sm0/n87 ), 
	.IN4(\shift_register_sm0/n29 ), 
	.IN3(\shift_register_sm0/out[8] ), 
	.IN2(data_out_to_data_in[0]), 
	.IN1(n57));
   AO22X1 U190 (.Q(\shift_register_sm0/n85 ), 
	.IN4(\shift_register_sm0/n26 ), 
	.IN3(\shift_register_sm0/out[7] ), 
	.IN2(n58), 
	.IN1(data_out_to_data_in[7]));
   AO22X1 U191 (.Q(\shift_register_sm0/n83 ), 
	.IN4(\shift_register_sm0/n26 ), 
	.IN3(\shift_register_sm0/out[6] ), 
	.IN2(n58), 
	.IN1(data_out_to_data_in[6]));
   AO22X1 U192 (.Q(\shift_register_sm0/n81 ), 
	.IN4(\shift_register_sm0/n26 ), 
	.IN3(\shift_register_sm0/out[5] ), 
	.IN2(n58), 
	.IN1(data_out_to_data_in[5]));
   AO22X1 U193 (.Q(\shift_register_sm0/n79 ), 
	.IN4(\shift_register_sm0/n26 ), 
	.IN3(\shift_register_sm0/out[4] ), 
	.IN2(n58), 
	.IN1(data_out_to_data_in[4]));
   AO22X1 U194 (.Q(\shift_register_sm0/n77 ), 
	.IN4(\shift_register_sm0/n26 ), 
	.IN3(\shift_register_sm0/out[3] ), 
	.IN2(n58), 
	.IN1(data_out_to_data_in[3]));
   AO22X1 U195 (.Q(\shift_register_sm0/n75 ), 
	.IN4(\shift_register_sm0/n26 ), 
	.IN3(\shift_register_sm0/out[2] ), 
	.IN2(n58), 
	.IN1(data_out_to_data_in[2]));
   AO22X1 U196 (.Q(\shift_register_sm0/n73 ), 
	.IN4(\shift_register_sm0/n26 ), 
	.IN3(\shift_register_sm0/out[1] ), 
	.IN2(n58), 
	.IN1(data_out_to_data_in[1]));
   AO22X1 U197 (.Q(\shift_register_sm0/n71 ), 
	.IN4(\shift_register_sm0/n26 ), 
	.IN3(\shift_register_sm0/out[0] ), 
	.IN2(n58), 
	.IN1(data_out_to_data_in[0]));
   AO22X1 U198 (.Q(\shift_register_sm0/n139 ), 
	.IN4(\shift_register_sm0/state[0] ), 
	.IN3(\shift_register_sm0/n49 ), 
	.IN2(n59), 
	.IN1(\shift_register_sm0/n68 ));
   INVX0 U199 (.QN(n59), 
	.IN(\shift_register_sm0/n49 ));
   NAND4X0 U200 (.QN(\shift_register_sm0/n68 ), 
	.IN4(n66), 
	.IN3(\shift_register_sm0/n62 ), 
	.IN2(n79), 
	.IN1(n76));
   AO22X1 U201 (.Q(\shift_register_sm0/n133 ), 
	.IN4(\shift_register_sm0/n33 ), 
	.IN3(\shift_register_sm0/out[31] ), 
	.IN2(data_out_to_data_in[7]), 
	.IN1(n61));
   AO22X1 U202 (.Q(\shift_register_sm0/n131 ), 
	.IN4(\shift_register_sm0/n33 ), 
	.IN3(\shift_register_sm0/out[30] ), 
	.IN2(data_out_to_data_in[6]), 
	.IN1(n61));
   AO22X1 U203 (.Q(\shift_register_sm0/n129 ), 
	.IN4(\shift_register_sm0/n33 ), 
	.IN3(\shift_register_sm0/out[29] ), 
	.IN2(data_out_to_data_in[5]), 
	.IN1(n61));
   AO22X1 U204 (.Q(\shift_register_sm0/n127 ), 
	.IN4(\shift_register_sm0/n33 ), 
	.IN3(\shift_register_sm0/out[28] ), 
	.IN2(data_out_to_data_in[4]), 
	.IN1(n61));
   AO22X1 U205 (.Q(\shift_register_sm0/n125 ), 
	.IN4(\shift_register_sm0/n33 ), 
	.IN3(\shift_register_sm0/out[27] ), 
	.IN2(data_out_to_data_in[3]), 
	.IN1(n61));
   AO22X1 U206 (.Q(\shift_register_sm0/n123 ), 
	.IN4(\shift_register_sm0/n33 ), 
	.IN3(\shift_register_sm0/out[26] ), 
	.IN2(data_out_to_data_in[2]), 
	.IN1(n61));
   AO22X1 U207 (.Q(\shift_register_sm0/n121 ), 
	.IN4(\shift_register_sm0/n33 ), 
	.IN3(\shift_register_sm0/out[25] ), 
	.IN2(data_out_to_data_in[1]), 
	.IN1(n61));
   AO22X1 U208 (.Q(\shift_register_sm0/n119 ), 
	.IN4(\shift_register_sm0/n33 ), 
	.IN3(\shift_register_sm0/out[24] ), 
	.IN2(data_out_to_data_in[0]), 
	.IN1(n61));
   AO22X1 U209 (.Q(\shift_register_sm0/n134 ), 
	.IN4(\shift_register_sm0/n35 ), 
	.IN3(n60), 
	.IN2(\shift_register_sm0/n34 ), 
	.IN1(shift_sr));
   INVX0 U210 (.QN(n60), 
	.IN(\shift_register_sm0/n34 ));
   NAND2X0 U211 (.QN(\shift_register_sm0/n34 ), 
	.IN2(\shift_register_sm0/n36 ), 
	.IN1(\shift_register_sm0/n32 ));
   OAI221X1 U212 (.QN(\shift_register_sm0/n36 ), 
	.IN5(\shift_register_sm0/n38 ), 
	.IN4(\divider_even0/rout ), 
	.IN3(\shift_register_sm0/n37 ), 
	.IN2(n71), 
	.IN1(n76));
   AO22X1 U213 (.Q(\shift_register_sm0/n138 ), 
	.IN4(\shift_register_sm0/n63 ), 
	.IN3(\shift_register_sm0/n50 ), 
	.IN2(\shift_register_sm0/state[3] ), 
	.IN1(\shift_register_sm0/n49 ));
   NAND4X0 U214 (.QN(\shift_register_sm0/n63 ), 
	.IN4(\shift_register_sm0/n65 ), 
	.IN3(\shift_register_sm0/n52 ), 
	.IN2(\shift_register_sm0/n44 ), 
	.IN1(\shift_register_sm0/n64 ));
   NAND3X0 U215 (.QN(\shift_register_sm0/n64 ), 
	.IN3(n83), 
	.IN2(\shift_register_sm0/state[1] ), 
	.IN1(\shift_register_sm0/state[2] ));
   NOR3X0 U216 (.QN(\shift_register_sm0/n65 ), 
	.IN3(n81), 
	.IN2(\shift_register_sm0/n40 ), 
	.IN1(n82));
   AO22X1 U217 (.Q(\counter_sm0/n32 ), 
	.IN4(\counter_sm0/n22 ), 
	.IN3(\counter_sm0/n21 ), 
	.IN2(\counter_sm0/state[1] ), 
	.IN1(n64));
   NAND3X0 U218 (.QN(\counter_sm0/n21 ), 
	.IN3(\counter_sm0/n23 ), 
	.IN2(\counter_sm0/n14 ), 
	.IN1(\counter_sm0/n13 ));
   OR2X1 U219 (.Q(\counter_sm0/n23 ), 
	.IN2(\counter_sm0/n8 ), 
	.IN1(\counter_sm0/n20 ));
   AO22X1 U220 (.Q(\shift_register_sm0/n135 ), 
	.IN4(\shift_register_sm0/n43 ), 
	.IN3(\shift_register_sm0/n42 ), 
	.IN2(\shift_register_sm0/n41 ), 
	.IN1(fifo_rd));
   NAND2X0 U221 (.QN(\shift_register_sm0/n43 ), 
	.IN2(\shift_register_sm0/n44 ), 
	.IN1(n79));
   NOR2X0 U222 (.QN(\shift_register_sm0/n42 ), 
	.IN2(\shift_register_sm0/n41 ), 
	.IN1(restart));
   AND4X1 U223 (.Q(\shift_register_sm0/n41 ), 
	.IN4(n66), 
	.IN3(\shift_register_sm0/n47 ), 
	.IN2(\shift_register_sm0/n46 ), 
	.IN1(\shift_register_sm0/n45 ));
   AO22X1 U224 (.Q(\shift_register0/n10 ), 
	.IN4(\shift_register0/n2 ), 
	.IN3(\shift_register0/shift_register[31] ), 
	.IN2(n54), 
	.IN1(data_out_shift_reg[31]));
   AO22X1 U225 (.Q(\shift_register_sm0/n137 ), 
	.IN4(\shift_register_sm0/n57 ), 
	.IN3(\shift_register_sm0/n50 ), 
	.IN2(\shift_register_sm0/state[1] ), 
	.IN1(\shift_register_sm0/n49 ));
   NAND4X0 U226 (.QN(\shift_register_sm0/n57 ), 
	.IN4(\shift_register_sm0/n60 ), 
	.IN3(\shift_register_sm0/n45 ), 
	.IN2(\shift_register_sm0/n59 ), 
	.IN1(\shift_register_sm0/n58 ));
   NAND2X0 U227 (.QN(\shift_register_sm0/n58 ), 
	.IN2(\shift_register_sm0/n19 ), 
	.IN1(n83));
   AND3X1 U228 (.Q(\shift_register_sm0/n60 ), 
	.IN3(\shift_register_sm0/n61 ), 
	.IN2(\shift_register_sm0/n38 ), 
	.IN1(\shift_register_sm0/n37 ));
   NAND3X0 U229 (.QN(\counter_sm0/n13 ), 
	.IN3(\counter_sm0/state[0] ), 
	.IN2(\counter_sm0/n5 ), 
	.IN1(\counter_sm0/n7 ));
   NAND3X0 U230 (.QN(\shift_register_sm0/n44 ), 
	.IN3(\shift_register_sm0/state[0] ), 
	.IN2(\shift_register_sm0/n19 ), 
	.IN1(\shift_register_sm0/n67 ));
   NAND3X0 U231 (.QN(\counter_sm0/n12 ), 
	.IN3(\counter_sm0/state[1] ), 
	.IN2(\counter_sm0/n5 ), 
	.IN1(\counter_sm0/state[0] ));
   NAND2X0 U232 (.QN(\shift_register_sm0/n59 ), 
	.IN2(\shift_register_sm0/n15 ), 
	.IN1(\shift_register_sm0/n56 ));
   NAND3X0 U233 (.QN(\shift_register_sm0/n61 ), 
	.IN3(\shift_register_sm0/n56 ), 
	.IN2(\shift_register_sm0/state[3] ), 
	.IN1(\shift_register_sm0/state[2] ));
   NAND3X0 U234 (.QN(\counter_sm0/n31 ), 
	.IN3(\counter_sm0/n12 ), 
	.IN2(\counter_sm0/n20 ), 
	.IN1(\counter_sm0/n19 ));
   NAND2X0 U235 (.QN(\counter_sm0/n19 ), 
	.IN2(\counter_sm0/state[2] ), 
	.IN1(n64));
   NOR2X0 U236 (.QN(\divider_even0/N4 ), 
	.IN2(\divider_even0/rout ), 
	.IN1(\shift_register_sm0/n24 ));
   NAND2X0 U237 (.QN(\shift_register_sm0/n47 ), 
	.IN2(\shift_register_sm0/n15 ), 
	.IN1(\shift_register_sm0/state[0] ));
   NAND3X0 U238 (.QN(\mem_to_fifo_sm0/n14 ), 
	.IN3(\mem_to_fifo_sm0/n26 ), 
	.IN2(\mem_to_fifo_sm0/n7 ), 
	.IN1(reset_n));
   NAND2X0 U239 (.QN(\mem_to_fifo_sm0/n26 ), 
	.IN2(\mem_to_fifo_sm0/n12 ), 
	.IN1(\mem_to_fifo_sm0/n20 ));
   AO22X1 U240 (.Q(\counter_sm0/n29 ), 
	.IN4(\counter_sm0/n11 ), 
	.IN3(restart), 
	.IN2(reset_n), 
	.IN1(n68));
   INVX0 U241 (.QN(n68), 
	.IN(\counter_sm0/n14 ));
   AO21X1 U242 (.Q(\counter_sm0/n11 ), 
	.IN3(\shift_register_sm0/n24 ), 
	.IN2(\counter_sm0/n13 ), 
	.IN1(\counter_sm0/n12 ));
   AO22X1 U243 (.Q(\mem_to_fifo_sm0/n30 ), 
	.IN4(\mem_to_fifo_sm0/n16 ), 
	.IN3(n62), 
	.IN2(\mem_to_fifo_sm0/n14 ), 
	.IN1(ROM_addr[0]));
   NAND2X0 U244 (.QN(\mem_to_fifo_sm0/n16 ), 
	.IN2(\mem_to_fifo_sm0/n18 ), 
	.IN1(\mem_to_fifo_sm0/n17 ));
   AO22X1 U245 (.Q(\shift_register_sm0/n117 ), 
	.IN4(\shift_register_sm0/n31 ), 
	.IN3(\shift_register_sm0/out[23] ), 
	.IN2(data_out_to_data_in[7]), 
	.IN1(n56));
   AO22X1 U246 (.Q(\shift_register_sm0/n115 ), 
	.IN4(\shift_register_sm0/n31 ), 
	.IN3(\shift_register_sm0/out[22] ), 
	.IN2(data_out_to_data_in[6]), 
	.IN1(n56));
   AO22X1 U247 (.Q(\shift_register_sm0/n113 ), 
	.IN4(\shift_register_sm0/n31 ), 
	.IN3(\shift_register_sm0/out[21] ), 
	.IN2(data_out_to_data_in[5]), 
	.IN1(n56));
   AO22X1 U248 (.Q(\shift_register_sm0/n111 ), 
	.IN4(\shift_register_sm0/n31 ), 
	.IN3(\shift_register_sm0/out[20] ), 
	.IN2(data_out_to_data_in[4]), 
	.IN1(n56));
   AO22X1 U249 (.Q(\shift_register_sm0/n109 ), 
	.IN4(\shift_register_sm0/n31 ), 
	.IN3(\shift_register_sm0/out[19] ), 
	.IN2(data_out_to_data_in[3]), 
	.IN1(n56));
   AO22X1 U250 (.Q(\shift_register_sm0/n107 ), 
	.IN4(\shift_register_sm0/n31 ), 
	.IN3(\shift_register_sm0/out[18] ), 
	.IN2(data_out_to_data_in[2]), 
	.IN1(n56));
   AO22X1 U251 (.Q(\shift_register_sm0/n105 ), 
	.IN4(\shift_register_sm0/n31 ), 
	.IN3(\shift_register_sm0/out[17] ), 
	.IN2(data_out_to_data_in[1]), 
	.IN1(n56));
   AO22X1 U252 (.Q(\shift_register_sm0/n103 ), 
	.IN4(\shift_register_sm0/n31 ), 
	.IN3(\shift_register_sm0/out[16] ), 
	.IN2(data_out_to_data_in[0]), 
	.IN1(n56));
   AO22X1 U253 (.Q(\counter_sm0/n33 ), 
	.IN4(\counter_sm0/n8 ), 
	.IN3(n70), 
	.IN2(\counter_sm0/n27 ), 
	.IN1(\counter_sm0/n26 ));
   AO22X1 U254 (.Q(\counter_sm0/n27 ), 
	.IN4(\counter_sm0/n28 ), 
	.IN3(\counter_sm0/state[1] ), 
	.IN2(n65), 
	.IN1(\counter_sm0/state[0] ));
   INVX0 U255 (.QN(n70), 
	.IN(\counter_sm0/n26 ));
   OA21X1 U256 (.Q(\counter_sm0/n26 ), 
	.IN3(\counter_sm0/n20 ), 
	.IN2(\counter_sm0/state[2] ), 
	.IN1(\counter_sm0/n7 ));
   AO22X1 U257 (.Q(\mem_to_fifo_sm0/n29 ), 
	.IN4(\mem_to_fifo_sm0/n15 ), 
	.IN3(n62), 
	.IN2(\mem_to_fifo_sm0/n14 ), 
	.IN1(ROM_addr[1]));
   NAND2X0 U258 (.QN(\counter_sm0/n20 ), 
	.IN2(\counter_sm0/n7 ), 
	.IN1(\counter_sm0/state[2] ));
   AO22X1 U259 (.Q(\shift_register0/n41 ), 
	.IN4(\shift_register0/n4 ), 
	.IN3(\shift_register0/shiftnextbit ), 
	.IN2(n55), 
	.IN1(shift_sr));
   AO22X1 U260 (.Q(\shift_register0/n8 ), 
	.IN4(n75), 
	.IN3(\shift_register0/shift_register[0] ), 
	.IN2(\shift_register0/n5 ), 
	.IN1(LED));
   INVX0 U261 (.QN(n75), 
	.IN(\shift_register0/n5 ));
   NAND2X0 U262 (.QN(\shift_register0/n5 ), 
	.IN2(n55), 
	.IN1(shift_sr));
   AO22X1 U263 (.Q(\mem_to_fifo_sm0/n32 ), 
	.IN4(\mem_to_fifo_sm0/n7 ), 
	.IN3(\mem_to_fifo_sm0/n22 ), 
	.IN2(n67), 
	.IN1(\mem_to_fifo_sm0/state[1] ));
   NAND2X0 U264 (.QN(\mem_to_fifo_sm0/n22 ), 
	.IN2(\mem_to_fifo_sm0/n18 ), 
	.IN1(\mem_to_fifo_sm0/n23 ));
   AO22X1 U265 (.Q(\mem_to_fifo_sm0/n31 ), 
	.IN4(\mem_to_fifo_sm0/n7 ), 
	.IN3(\mem_to_fifo_sm0/n19 ), 
	.IN2(n67), 
	.IN1(\mem_to_fifo_sm0/state[2] ));
   NAND2X0 U266 (.QN(\mem_to_fifo_sm0/n19 ), 
	.IN2(\mem_to_fifo_sm0/n21 ), 
	.IN1(\mem_to_fifo_sm0/n20 ));
   NAND2X0 U267 (.QN(\counter_sm0/n28 ), 
	.IN2(\counter_sm0/n8 ), 
	.IN1(sensor));
   NAND2X0 U268 (.QN(\counter_sm0/n18 ), 
	.IN2(\counter_sm0/n8 ), 
	.IN1(\counter_sm0/state[1] ));
   NAND4X0 U269 (.QN(\mem_to_fifo_sm0/n33 ), 
	.IN4(\mem_to_fifo_sm0/n25 ), 
	.IN3(\mem_to_fifo_sm0/n24 ), 
	.IN2(\mem_to_fifo_sm0/n7 ), 
	.IN1(\mem_to_fifo_sm0/n10 ));
   OA21X1 U270 (.Q(\mem_to_fifo_sm0/n25 ), 
	.IN3(\mem_to_fifo_sm0/n21 ), 
	.IN2(\mem_to_fifo_sm0/n6 ), 
	.IN1(\mem_to_fifo_sm0/N43 ));
   INVX0 U271 (.QN(\mem_to_fifo_sm0/n7 ), 
	.IN(restart_mem));
   NAND2X0 U272 (.QN(\mem_to_fifo_sm0/n28 ), 
	.IN2(\mem_to_fifo_sm0/n9 ), 
	.IN1(\mem_to_fifo_sm0/n8 ));
   OR2X1 U273 (.Q(\mem_to_fifo_sm0/n9 ), 
	.IN2(restart_mem), 
	.IN1(\mem_to_fifo_sm0/n10 ));
   NAND4X0 U274 (.QN(\mem_to_fifo_sm0/n8 ), 
	.IN4(\mem_to_fifo_sm0/n7 ), 
	.IN3(\mem_to_fifo_sm0/n12 ), 
	.IN2(\mem_to_fifo_sm0/n11 ), 
	.IN1(fifo_wr));
   NAND3X0 U275 (.QN(\mem_to_fifo_sm0/n11 ), 
	.IN3(\mem_to_fifo_sm0/state[2] ), 
	.IN2(\mem_to_fifo_sm0/state[1] ), 
	.IN1(\mem_to_fifo_sm0/state[0] ));
   NAND3X0 U276 (.QN(\mem_to_fifo_sm0/n17 ), 
	.IN3(\mem_to_fifo_sm0/state[0] ), 
	.IN2(n73), 
	.IN1(\mem_to_fifo_sm0/state[1] ));
   NAND3X0 U277 (.QN(\mem_to_fifo_sm0/n18 ), 
	.IN3(\mem_to_fifo_sm0/state[2] ), 
	.IN2(\mem_to_fifo_sm0/n5 ), 
	.IN1(\mem_to_fifo_sm0/state[0] ));
   NAND3X0 U278 (.QN(\mem_to_fifo_sm0/n12 ), 
	.IN3(\mem_to_fifo_sm0/state[0] ), 
	.IN2(\mem_to_fifo_sm0/n5 ), 
	.IN1(n73));
   NAND3X0 U279 (.QN(\mem_to_fifo_sm0/n21 ), 
	.IN3(\mem_to_fifo_sm0/state[2] ), 
	.IN2(\mem_to_fifo_sm0/n6 ), 
	.IN1(\mem_to_fifo_sm0/state[1] ));
   NAND3X0 U280 (.QN(\mem_to_fifo_sm0/n10 ), 
	.IN3(\mem_to_fifo_sm0/state[1] ), 
	.IN2(\mem_to_fifo_sm0/n6 ), 
	.IN1(n73));
   NAND3X0 U281 (.QN(\mem_to_fifo_sm0/n24 ), 
	.IN3(\mem_to_fifo_sm0/state[2] ), 
	.IN2(\mem_to_fifo_sm0/n5 ), 
	.IN1(\mem_to_fifo_sm0/n6 ));
   INVX0 U282 (.QN(n65), 
	.IN(sensor));
   INVX0 U283 (.QN(\shift_register_sm0/n23 ), 
	.IN(fifo_empty));
endmodule

